FROM golang:1.18-alpine

RUN mkdir /app

RUN addgroup -S testgroup
RUN adduser -S -D -h /app testuser testgroup
RUN chown -R testuser:testroup /app

USER testuser

COPY main.go /app

EXPOSE 8080
CMD go run /app/main.go